name: 'Provision Infrastructure'
on:
  push:
    branches: [ "main" ]
env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }} 
    AWS_REGION: ${{secrets.AWS_REGION}}   
    ENV: dev
jobs:
  terraform:
    name: 'Deploying Resources'
    runs-on: ubuntu-latest
    environment: development
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform init
    
    - name: Terraform Format
      run: terraform fmt -check
    
    - name: Terraform Plan
      run: |
        pwd
        ls
        terraform plan -out=plan.tfplan --var-file=./configs/$ENV.tfvars --input=false

    - name: Terraform Apply
      run: terraform apply -auto-approve -input=false "plan.tfplan"
